Change form id attribute to form-id to support spaces
enketo/enketo-transformer pull request #102
Opened 2021-05-05 20:41 UTC by lognaturel

Closes #100 

As discussed in #100, spaces were previously replaced because the `id` attribute is well-known in HTML and is not supposed to contain spaces. This PR introduces a custom attribute named `form-id` with no value restrictions and removes the `id` attribute.

We discussed just using spaces in the `id` attribute value but the risk there is that some browser e.g. chooses to truncate on the space now or in the future. There is value to putting an `id` on a `form` but only [to have form elements outside the `form` block](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefform). If this were desirable in some future, `id` could be added back in with a transformation to replace spaces (or just using something generic like `form1`).

As far as I can tell, the form id is only used to communicate with other Enketo tools so changing the attribute name is not a big deal. I briefly looked at [dependent packages](https://github.com/enketo/enketo-transformer/network/dependents?package_id=UGFja2FnZS0xODA5ODgxMA%3D%3D) and they're all either core Enketo tools, forks of core Enketo tools, or no longer maintained. Still, it is a breaking change. We could also keep the `id` element as-is for backwards compatibility.

I'll follow up with PRs to update dependent tools using a to-be-released v1.43.0.

(Side note. Technically the `id` and `xmlns` blocks are in the wrong order: "If specified, the id value takes precedence over any explicit xmlns declaration." [source](https://docs.getodk.org/openrosa-metadata/#form-identity). Don't think this matters much since I've never seen a form that uses a namespace for this but I can flip them in this PR if desired.)

2021-05-05 20:47 UTC, lognaturel commented
When you have a chance, @eyelidlessness, would be great to get a first pass at review from you!

2021-05-08 23:28 UTC, eyelidlessness requested changes
Maybe a bit of bike shedding, but I think it's worth the minor change to `data-form-id`.

2021-05-08 23:28 UTC, eyelidlessness commented on src/xsl/openrosa2html5form.xsl
> +                    <xsl:attribute name="form-id">
In the interest of HTML validity/forward-compatibility, and consistency with similar attribute transformations, I think it's safer to use `data-form-id`. The `data-` prefix is the namespace for arbitrary custom attributes, and will also populate `form.dataset` for consistent access.

2021-05-10 18:41 UTC, eyelidlessness approved these changes
Looks good to me!

2021-05-11 20:00 UTC, MartijnR approved these changes
Great, thank you!

Hopefully, this is the only place that it is used in the rest of Enketo: https://github.com/enketo/enketo-core/blob/master/src/js/form.js#L160

2021-05-11 20:00 UTC, merged