Reorganize README
enketo/enketo-transformer pull request #174
Opened 2023-03-16 21:14 UTC by lognaturel

Small order-only changes to hopefully make the README flow a bit better.

2023-03-16 21:16 UTC, lognaturel commented on README.md
> +## Interactive web demo
I could be convinced that moving this up is bad. I like that it answers the question "how can I just see what this thing does"

2023-03-16 21:35 UTC, eyelidlessness requested changes

2023-03-16 21:35 UTC, eyelidlessness commented on README.md
> +#### Prerequisites
This feels a bit awkward to me:

- Node is a prerequisite for all usage
- Node 16/NPM 6 restrictions are only pertinent for Node usage, but currently will still apply for web usage
- Volta is really only pertinent for development _in_ Transformer

Maybe we should move this up, and change the Volta recommendation wording to reflect that?

2023-03-17 17:52 UTC, eyelidlessness approved these changes
@lognaturel I'll let you merge if you're good with my change.

2023-03-17 18:50 UTC, merged